#!/usr/bin/env python3
"""Which entry points does *this* implementation actually have?

Decision 6 says functions the implementation lacks return
MPI_ERR_UNSUPPORTED_OPERATION from generated `#ifdef` stubs. This is what those
`#ifdef`s test: it writes `mpiwrapper_impl_config.h`, defining
MPIWRAPPER_HAVE_MPI_Foo for every entry point the implementation declares, and
gen/mpiwrapper/wrappers.c stubs the rest.

**Why not a version test.** `#if MPI_VERSION >= 4` was the obvious spelling and
is wrong in both directions. Open MPI 5.0.10 reports MPI-3.1 and has sessions
and partitioned communication, so a version test would stub what is there; and
the ABI is MPI-5.0 while the enforced floor is MPI-3.0 (decision 3), so the gap
is 200-odd entry points rather than a handful. Asking the implementation's own
header is exact, and it is the same header the wrapper bodies are compiled
against.

**Why not nm.** The library's symbol table misses what the header provides as a
macro -- Open MPI defines MPI_Aint_add that way -- and a macro is perfectly
callable. The compiler is the only thing that answers the question the
generated code actually asks.

**What gets probed** is read out of the generated sources: every
`MPIWRAPPER_HAVE_<name>` they mention, and nothing else. So the generator
decides what needs asking and the two cannot drift apart. Most of those names
are entry points; a few are the integer-family constants that a conforming
implementation may not have, which cannot be tested with `#ifdef` because both
implementations spell some of them as enumerators.

**How.** One probe per name, each on its own line of a single translation unit,
compiled with -fsyntax-only. A name that is a macro answers `#ifdef`; anything
else has to be declared for `sizeof &name` to compile. If the compile fails,
the diagnostics' *line numbers* -- not their wording -- say which probes are
bad; those are dropped and the file is compiled again, so the answer is always
confirmed by a compile that succeeds. Two or three rounds is typical, and
nothing about the parse depends on a compiler's phrasing.

Everything here is compile-only, so it works when cross-compiling (NOTES.md
#9).

Usage:
  dev/probe_entrypoints.py --cc CC --out FILE [--flag F]... [--entrypoints F]
"""

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ENTRYPOINTS = ROOT / "dev" / "entrypoints.txt"
DEFAULT_SOURCES = [ROOT / "gen" / "mpiwrapper" / "wrappers.c",
                   ROOT / "gen" / "mpiwrapper" / "constants.c"]

_LINE_RE = re.compile(r"^[^\s].*?:(\d+):(?:\d+:)?\s*(?:fatal\s+)?error:",
                      re.MULTILINE)


def probe_source(names):
    """The probe TU, and a line -> name map for reading the diagnostics."""
    lines = [
        "/* Generated by dev/probe_entrypoints.py; compiled, never run. */",
        "#include <mpi.h>",
        "int mpiwrapper_probe(void);",
        "int mpiwrapper_probe(void)",
        "{",
        "  int n = 0;",
    ]
    where = {}
    for name in names:
        lines.append(f"#ifdef {name}")
        lines.append("  n += 1;")
        lines.append("#else")
        where[len(lines) + 1] = name
        lines.append(f"  n += (int)sizeof &{name};")
        lines.append("#endif")
    lines.append("  return n;")
    lines.append("}")
    return "\n".join(lines) + "\n", where


def compile_ok(cc, flags, text, workdir):
    src = Path(workdir) / "probe.c"
    src.write_text(text)
    proc = subprocess.run([cc, "-fsyntax-only", *flags, str(src)],
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return proc.returncode == 0, proc.stdout.decode("utf-8", "replace")


def accepts(cc, flag, workdir):
    ok, _ = compile_ok(cc, [flag], "int main(void) { return 0; }", workdir)
    return ok


def probe(cc, flags, names):
    """The subset of `names` this implementation declares."""
    with tempfile.TemporaryDirectory() as workdir:
        # Report every error in one pass where the compiler can; without it
        # the loop below simply takes more rounds.
        for flag in ("-ferror-limit=0", "-fmax-errors=0"):
            if accepts(cc, flag, workdir):
                flags = [*flags, flag]
                break

        present = list(names)
        for round_ in range(1, 41):
            text, where = probe_source(present)
            ok, output = compile_ok(cc, flags, text, workdir)
            if ok:
                return present
            bad = {where[int(m.group(1))] for m in _LINE_RE.finditer(output)
                   if int(m.group(1)) in where}
            if not bad:
                sys.stderr.write(output)
                raise SystemExit(
                    "the probe failed for a reason that is not a missing entry "
                    "point (no diagnostic pointed at a probe line). The "
                    "compiler output is above; this is a real build problem "
                    "rather than an implementation without some MPI function.")
            present = [n for n in present if n not in bad]
    raise SystemExit("the probe did not converge in 40 rounds")


HEADER = """\
/* GENERATED at configure time by dev/probe_entrypoints.py -- do not edit and
 * do not commit. Says which MPI entry points the implementation this build
 * tree was configured against actually declares.
 *
 * gen/mpiwrapper/wrappers.c emits a real body for an entry point defined here
 * and decision 6's run-time-reporting stub for one that is not.
 */

#ifndef MPIWRAPPER_IMPL_CONFIG_H
#define MPIWRAPPER_IMPL_CONFIG_H

/* wrappers.c #errors without this: a missing probe would otherwise turn the
 * whole library into stubs, which links and loads and answers
 * MPI_ERR_UNSUPPORTED_OPERATION to everything.
 */
#define MPIWRAPPER_IMPL_PROBED 1

"""


def wanted(sources, entrypoints):
    """(guard name -> the spellings that must all be declared).

    An entry point needs both its MPI_ and PMPI_ names, because the body macro
    is instantiated once against each (decision 7).
    """
    bases = {ln.strip() for ln in entrypoints.read_text().split() if ln.strip()}
    out = {}
    for src in sources:
        for name in re.findall(r"MPIWRAPPER_HAVE_([A-Za-z_]\w*)",
                               src.read_text()):
            if name.startswith("MPI_") and name[len("MPI_"):] in bases:
                out[name] = (name, "P" + name)
            else:
                out[name] = (name,)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cc", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--flag", action="append", default=[])
    ap.add_argument("--entrypoints", default=str(DEFAULT_ENTRYPOINTS))
    ap.add_argument("--source", action="append", default=[],
                    help="a generated source to read MPIWRAPPER_HAVE_* from")
    args = ap.parse_args()

    sources = [Path(s) for s in args.source] or DEFAULT_SOURCES
    guards = wanted(sources, Path(args.entrypoints))
    if not guards:
        raise SystemExit("no MPIWRAPPER_HAVE_* names in " +
                         ", ".join(str(s) for s in sources))

    names = sorted({n for spellings in guards.values() for n in spellings})
    # A flag may arrive as one shell-quoted string from CMake's list handling.
    flags = [f for raw in args.flag for f in raw.split() if f]
    present = set(probe(args.cc, flags, names))

    have = sorted(g for g, spellings in guards.items()
                  if all(n in present for n in spellings))

    out = [HEADER]
    for name in have:
        out.append(f"#define MPIWRAPPER_HAVE_{name} 1")
    out.append("")
    out.append("#endif /* MPIWRAPPER_IMPL_CONFIG_H */")
    Path(args.out).write_text("\n".join(out) + "\n")

    print(f"probed {len(guards)} names: {len(have)} available, "
          f"{len(guards) - len(have)} absent from this implementation")


if __name__ == "__main__":
    main()
