/* Excerpt of the generated gen/include/mpiabi.h.
 *
 * The renamed view of the ABI, for libmpiwrapper to include *alongside* the
 * implementation's own <mpi.h>. Generated by textual transformation of the same
 * source as gen/include/mpi.h (the mpi-abi-stubs header plus doc/mpi.h.patch), so
 * no ABI value is ever transcribed by hand.
 *
 * Three rules govern the renaming, and each earns its keep:
 *
 *  1. Typedef names, macro names and enumerator names get the MPIABI_ prefix.
 *     That is what lets both views coexist in one translation unit, so a wrapper
 *     body can say `MPI_INT` for the implementation's datatype and
 *     `MPIABI_INT` for the ABI's in the same line of code.
 *
 *  2. Struct *tags* are left alone. `MPIABI_Comm` stays `struct MPI_ABI_Comm *`,
 *     which is the same type as the ABI header's own `MPI_Comm`. Renaming the tag
 *     would make them incompatible and force a cast in all 1376 forwarders on the
 *     ABI side -- casts that would then silently absorb a genuine type error.
 *
 *  3. Struct *member* names are left alone. Members live in a per-struct
 *     namespace, so MPIABI_Status.MPI_SOURCE and the implementation's
 *     MPI_Status.MPI_SOURCE cannot collide, and keeping them identical means the
 *     status conversion reads the way the standard describes it.
 *
 * Prototypes are dropped entirely: the wrapper calls the implementation, never
 * the ABI.
 *
 * Values below are the real ones, read out of the stub header.
 */

#ifndef MPIABI_H
#define MPIABI_H

#include <stdint.h>

#define MPIABI_VERSION 1

/* Handles: pointer-typed, so pointer-sized -- 32 bits on ILP32, which is why no
 * scheme here may rely on spare high bits.
 */
typedef struct MPI_ABI_Comm     *MPIABI_Comm;
typedef struct MPI_ABI_Datatype *MPIABI_Datatype;
typedef struct MPI_ABI_Request  *MPIABI_Request;
typedef struct MPI_ABI_Op       *MPIABI_Op;
typedef struct MPI_ABI_Info     *MPIABI_Info;
typedef struct MPI_ABI_File     *MPIABI_File;

#define MPIABI_COMM_NULL     ((MPIABI_Comm)0x00000100)
#define MPIABI_COMM_WORLD    ((MPIABI_Comm)0x00000101)
#define MPIABI_COMM_SELF     ((MPIABI_Comm)0x00000102)
#define MPIABI_FILE_NULL     ((MPIABI_File)0x00000118)
#define MPIABI_INFO_NULL     ((MPIABI_Info)0x00000130)
#define MPIABI_REQUEST_NULL  ((MPIABI_Request)0x00000180)
#define MPIABI_DATATYPE_NULL ((MPIABI_Datatype)0x00000200)
#define MPIABI_INT           ((MPIABI_Datatype)0x00000209)
#define MPIABI_DOUBLE        ((MPIABI_Datatype)0x00000214)
#define MPIABI_BYTE          ((MPIABI_Datatype)0x00000247)
#define MPIABI_OP_NULL       ((MPIABI_Op)0x00000020)
#define MPIABI_SUM           ((MPIABI_Op)0x00000021)

/* The predefined handle range, which the generator emits so that the collision
 * check in mpiwrapper_convert.c does not hard-code it.
 */
#define MPIABI_PREDEFINED_FIRST 0x00000020u
#define MPIABI_PREDEFINED_LAST  0x000002ebu

typedef struct {
  int MPI_SOURCE;
  int MPI_TAG;
  int MPI_ERROR;
  int MPI_internal[5];
} MPIABI_Status;

#define MPIABI_STATUS_IGNORE   ((MPIABI_Status *)0)
#define MPIABI_STATUSES_IGNORE ((MPIABI_Status *)0)

typedef void(MPIABI_User_function)(void *invec, void *inoutvec, int *len,
                                  MPIABI_Datatype *datatype);

enum {
  MPIABI_SUCCESS                   = 0,
  MPIABI_ERR_COUNT                 = 2,
  MPIABI_ERR_INTERN                = 17,
  MPIABI_ERR_IN_STATUS             = 19,
  MPIABI_ERR_INFO_KEY              = 31,
  MPIABI_ERR_PORT                  = 43,
  MPIABI_ERR_UNSUPPORTED_OPERATION = 55,
  MPIABI_ERR_LASTCODE              = 16383
};

enum {
  MPIABI_ANY_SOURCE = -1,
  MPIABI_ANY_TAG    = -2,
  MPIABI_PROC_NULL  = -3,
  MPIABI_ROOT       = -4,
  MPIABI_UNDEFINED  = -32766
};

/* Bit assignments unrelated to any implementation's -- hence the OR-decomposition
 * in mpiwrapper_convert.c rather than a switch.
 */
enum {
  MPIABI_MODE_APPEND          = 1,
  MPIABI_MODE_CREATE          = 2,
  MPIABI_MODE_DELETE_ON_CLOSE = 4,
  MPIABI_MODE_EXCL            = 8,
  MPIABI_MODE_RDONLY          = 16,
  MPIABI_MODE_RDWR            = 32,
  MPIABI_MODE_SEQUENTIAL      = 64,
  MPIABI_MODE_UNIQUE_OPEN     = 128,
  MPIABI_MODE_WRONLY          = 256
};

#define MPIABI_MAX_ERROR_STRING 512

#endif /* MPIABI_H */
